import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dinidu
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        
    }
    
    public void addtable ( int id , String Name, int Qty, Double Price){
        
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        
        DecimalFormat df= new DecimalFormat("00.00");
        double totPrice = Price * Double.valueOf(Qty);
        String TotalPrice = df.format(totPrice);
        
        
        for (int row = 0; row < jTable1.getRowCount(); row++){
            
            if (Name == jTable1.getValueAt(row, 1))
            {
                dt.removeRow(jTable1.convertRowIndexToModel(row));
            }
        }
        
        
        
        
        
        Vector v= new Vector ();
       
        v.add(id);
        v.add(Name);
        v.add(Qty);
        v.add(TotalPrice);
        
        dt.addRow(v);
        
      
    
    }
    
    public void cal(){
        
        
        int numOfRow = jTable1.getRowCount();
        double  Total = 0.0;
        
        for (int i = 0; i < numOfRow; i++){
            double value = Double.valueOf(jTable1.getValueAt(i,3).toString());
        
            Total += value;
            
            
            
        }
        
        DecimalFormat df = new DecimalFormat("");
        Tot.setText(df.format(Total));
        
            
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        SE1 = new javax.swing.JButton();
        SE2 = new javax.swing.JButton();
        SE3 = new javax.swing.JButton();
        SE4 = new javax.swing.JButton();
        SE5 = new javax.swing.JButton();
        SE6 = new javax.swing.JButton();
        SE7 = new javax.swing.JButton();
        SE8 = new javax.swing.JButton();
        SE9 = new javax.swing.JButton();
        SE10 = new javax.swing.JButton();
        SE11 = new javax.swing.JButton();
        SE12 = new javax.swing.JButton();
        LA6 = new javax.swing.JLabel();
        LA7 = new javax.swing.JLabel();
        LA8 = new javax.swing.JLabel();
        LA9 = new javax.swing.JLabel();
        LA10 = new javax.swing.JLabel();
        LA11 = new javax.swing.JLabel();
        LA12 = new javax.swing.JLabel();
        LA13 = new javax.swing.JLabel();
        LA14 = new javax.swing.JLabel();
        LA15 = new javax.swing.JLabel();
        LA16 = new javax.swing.JLabel();
        LA17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        S11 = new javax.swing.JButton();
        LA19 = new javax.swing.JLabel();
        S12 = new javax.swing.JButton();
        LA20 = new javax.swing.JLabel();
        S13 = new javax.swing.JButton();
        LA21 = new javax.swing.JLabel();
        S14 = new javax.swing.JButton();
        LA22 = new javax.swing.JLabel();
        S15 = new javax.swing.JButton();
        LA23 = new javax.swing.JLabel();
        S16 = new javax.swing.JButton();
        LA24 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        DI1 = new javax.swing.JButton();
        DI2 = new javax.swing.JButton();
        LA29 = new javax.swing.JLabel();
        LA30 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        DR1 = new javax.swing.JButton();
        DR2 = new javax.swing.JButton();
        LA31 = new javax.swing.JLabel();
        LA32 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        LA1 = new javax.swing.JLabel();
        LA2 = new javax.swing.JLabel();
        LA3 = new javax.swing.JLabel();
        LA4 = new javax.swing.JLabel();
        LA5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        b = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        total = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Tot = new javax.swing.JLabel();
        Bal = new javax.swing.JLabel();
        pay = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jButton1.setText("Short eats");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sweets");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Lunch");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Drinks");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Others");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Bread");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Back))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back)
                .addGap(59, 59, 59)
                .addComponent(jButton6)
                .addGap(23, 23, 23)
                .addComponent(jButton1)
                .addGap(22, 22, 22)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        SE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/egg roll.jpg"))); // NOI18N
        SE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SE1ActionPerformed(evt);
            }
        });

        SE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fish roll.jpg"))); // NOI18N
        SE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SE2ActionPerformed(evt);
            }
        });

        SE3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c pastry.jpg"))); // NOI18N
        SE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SE3ActionPerformed(evt);
            }
        });

        SE4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/egg sini pastry.jpg"))); // NOI18N
        SE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SE4ActionPerformed(evt);
            }
        });

        SE5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza.jpg"))); // NOI18N
        SE5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SE5ActionPerformed(evt);
            }
        });

        SE6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/omlet bun.jpg"))); // NOI18N
        SE6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SE6ActionPerformed(evt);
            }
        });

        SE7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sausage bun.jpg"))); // NOI18N
        SE7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SE7ActionPerformed(evt);
            }
        });

        SE8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sausage jambo.jpg"))); // NOI18N
        SE8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SE8ActionPerformed(evt);
            }
        });

        SE9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinisambal bun.jpg"))); // NOI18N
        SE9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SE9ActionPerformed(evt);
            }
        });

        SE10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fishbun.jpg"))); // NOI18N
        SE10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SE10ActionPerformed(evt);
            }
        });

        SE11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fishcake.jpg"))); // NOI18N
        SE11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SE11ActionPerformed(evt);
            }
        });

        SE12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drumstick.jpg"))); // NOI18N
        SE12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SE12ActionPerformed(evt);
            }
        });

        LA6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA6.setText("0");

        LA7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA7.setText("0");

        LA8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA8.setText("0");

        LA9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA9.setText("0");

        LA10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA10.setText("0");

        LA11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA11.setText("0");

        LA12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA12.setText("0");

        LA13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA13.setText("0");

        LA14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA14.setText("0");

        LA15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA15.setText("0");

        LA16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA16.setText("0");

        LA17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA17.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LA6, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(SE4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(LA9, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(SE1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SE5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(LA10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))
                            .addComponent(SE2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LA7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SE7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LA15, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SE8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LA16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LA12, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(SE10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SE11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LA13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SE3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SE9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LA11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LA8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SE6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LA14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SE12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LA17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SE1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SE3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SE2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LA6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LA8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LA7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SE5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SE4)
                        .addComponent(SE6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LA9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LA11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LA10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SE8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SE7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SE9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LA12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LA13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LA14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SE10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SE11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SE12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LA15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LA16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LA17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131))
        );

        jTabbedPane1.addTab("Tab1", jPanel3);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        S11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cream.jpg"))); // NOI18N
        S11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S11ActionPerformed(evt);
            }
        });

        LA19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA19.setText("0");

        S12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crocbun.jpg"))); // NOI18N
        S12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S12ActionPerformed(evt);
            }
        });

        LA20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA20.setText("0");

        S13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eclars.jpg"))); // NOI18N
        S13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S13ActionPerformed(evt);
            }
        });

        LA21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA21.setText("0");

        S14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jam bun.jpg"))); // NOI18N
        S14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S14ActionPerformed(evt);
            }
        });

        LA22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA22.setText("0");

        S15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sini bun.jpg"))); // NOI18N
        S15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S15ActionPerformed(evt);
            }
        });

        LA23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA23.setText("0");

        S16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sponge cake.jpg"))); // NOI18N
        S16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S16ActionPerformed(evt);
            }
        });

        LA24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA24.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LA22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(S14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(LA19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(S11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(S15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(LA20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(S12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LA23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(86, 86, 86)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LA24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(S16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(LA21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(S13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(S12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(S13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(S11))
                .addGap(3, 3, 3)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LA20, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addComponent(LA19, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                    .addComponent(LA21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(S14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(S15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(S16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LA22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LA23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LA24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(356, 356, 356))
        );

        jTabbedPane1.addTab("Tab2", jPanel6);

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));

        DI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c lunch.jpg"))); // NOI18N
        DI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DI1ActionPerformed(evt);
            }
        });

        DI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fish lunch.jpg"))); // NOI18N
        DI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DI2ActionPerformed(evt);
            }
        });

        LA29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA29.setText("0");

        LA30.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA30.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LA29, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(DI1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(72, 72, 72)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LA30, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(DI2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DI1)
                    .addComponent(DI2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LA29, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LA30, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(516, 516, 516))
        );

        jTabbedPane1.addTab("Tab3", jPanel7);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        DR1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nescafe.jpg"))); // NOI18N
        DR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DR1ActionPerformed(evt);
            }
        });

        DR2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nestea.jpg"))); // NOI18N
        DR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DR2ActionPerformed(evt);
            }
        });

        LA31.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA31.setText("0");

        LA32.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA32.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DR1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LA31, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DR2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LA32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DR1)
                    .addComponent(DR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LA31, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(LA32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(506, 506, 506))
        );

        jTabbedPane1.addTab("Tab4", jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tab5", jPanel5);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/achchu.jpg"))); // NOI18N
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roast bread.jpg"))); // NOI18N
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sandwich.jpg"))); // NOI18N
        B3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slied bread.jpg"))); // NOI18N
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Thati.jpg"))); // NOI18N
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        LA1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA1.setText("0");

        LA2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA2.setText("0");

        LA3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA3.setText("0");

        LA4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA4.setText("0");

        LA5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LA5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LA5.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LA1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(LA5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(B5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(LA2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LA3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(LA4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(B1))
                        .addComponent(B2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(B3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LA1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LA3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LA2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LA4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LA5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(361, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tab6", jPanel2);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Items", "Qty", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        b.setColumns(20);
        b.setRows(5);
        jScrollPane2.setViewportView(b);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        total.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        total.setText("Total :");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Cash :");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Balance :");

        Tot.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Tot.setText("00");

        Bal.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Bal.setText("00");

        pay.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton7.setText("Pay");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton8.setText("Print");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(Tot, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(Bal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(195, 195, 195)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total)
                            .addComponent(Tot))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Bal)))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 102, 255));
        jButton9.setText("Clear");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
 Options1 op1 = new Options1();
  op1.setVisible(true);
  this.setVisible(false);
  
        
        
    }//GEN-LAST:event_BackActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here
           // Get the table model
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Clear all rows
    model.setRowCount(0);
    Tot.setText(null);
    pay.setText(null);
    Bal.setText(null);
    b.setText(null);
LA1.setText("0");
LA2.setText("0");
LA3.setText("0");
LA4.setText("0");
LA5.setText("0");
LA6.setText("0");
LA7.setText("0");
LA8.setText("0");
LA9.setText("0");
LA10.setText("0");
LA11.setText("0");
LA12.setText("0");
LA13.setText("0");
LA14.setText("0");
LA15.setText("0");
LA16.setText("0");
LA17.setText("0");
LA19.setText("0");
LA20.setText("0");
LA21.setText("0");
LA22.setText("0");
LA23.setText("0");
LA24.setText("0");
LA29.setText("0");
LA30.setText("0");
LA31.setText("0");
LA32.setText("0");


                
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
        // Remove commas and parse text field values as integers
        int tot = Integer.parseInt(Tot.getText().replaceAll(",", ""));
        int paid = Integer.parseInt(pay.getText().replaceAll(",", ""));

        int balance = paid - tot;
        Bal.setText(String.valueOf(balance));
    } catch (NumberFormatException e) {
        // Handle if the text fields contain non-numeric values
        JOptionPane.showMessageDialog(null, "Invalid input. Please enter numeric values.");
    }
                
                
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // Bill Print:
        
        try {
            b.setText("\t *Bake Zone* \n ");
            b.setText( b.getText()+"\t    Divulapitiya \n ");
            b.setText( b.getText()+"\t    08/08 \n ");
            b.setText( b.getText()+"\t  Sri Lanka \n ");
            b.setText( b.getText()+ "................................................................................. \n ");
            b.setText( b.getText()+" Item \t Qty \t Price" + "\n");
            b.setText( b.getText()+ ".................................................................................. \n ");
            
                  
            DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
            
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                
                String Name = df.getValueAt(i,1).toString();
                String Qty = df.getValueAt(i,2).toString();
                String Price = df.getValueAt(i,3).toString();
                
                b.setText(b.getText()+" "+ Name + "\t" + Qty + "\t" + Price +"\n");
                
                  
            }
            b.setText(b.getText()+ "................................................................................. \n ");
            b.setText(b.getText() + "Sub Total    :" + Tot.getText()+"\n");
            b.setText(b.getText() + " Cash           :" + pay.getText()+"\n");
            b.setText(b.getText() + " Balance      :" + Bal.getText()+"\n");
            b.setText(b.getText()+ "................................................................................. \n ");
            b.setText(b.getText()+ "Thank You, Come Again.....!" + "\n");
            
            b.print();
            
        } catch (Exception e){
            
            System.out.println(e);
            
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA5.getText());
        ++i;
        LA5.setText(String.valueOf(i));

        addtable(005,"Thati",i,190.00);
        cal();
    }//GEN-LAST:event_B5ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA4.getText());
        ++i;
        LA4.setText(String.valueOf(i));

        addtable(004,"Slied Bread",i,220.00);
        cal();
    }//GEN-LAST:event_B4ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA3.getText());
        ++i;
        LA3.setText(String.valueOf(i));

        addtable(003,"Sandwich",i,210.00);
        cal();
    }//GEN-LAST:event_B3ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA2.getText());
        ++i;
        LA2.setText(String.valueOf(i));

        addtable(002,"Roast Bread",i,65.00);
        cal();
    }//GEN-LAST:event_B2ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed

        // TODO add your handling code here:
        int i = Integer.valueOf(LA1.getText());
        ++i;
        LA1.setText(String.valueOf(i));

        addtable(001,"Achchu Bread",i,190.00);

        cal();

    }//GEN-LAST:event_B1ActionPerformed

    private void DR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DR2ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA32.getText());
        ++i;
        LA32.setText(String.valueOf(i));

        addtable(32,"Nestea",i,400.00);
        cal();
    }//GEN-LAST:event_DR2ActionPerformed

    private void DR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DR1ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA31.getText());
        ++i;
        LA31.setText(String.valueOf(i));

        addtable(31,"Nescafe",i,100.00);
        cal();
    }//GEN-LAST:event_DR1ActionPerformed

    private void DI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DI2ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA30.getText());
        ++i;
        LA30.setText(String.valueOf(i));

        addtable(30,"Fish Lunch ",i,350.00);
        cal();
    }//GEN-LAST:event_DI2ActionPerformed

    private void DI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DI1ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA29.getText());
        ++i;
        LA29.setText(String.valueOf(i));

        addtable(29,"Chicken Lunch",i,400.00);
        cal();
    }//GEN-LAST:event_DI1ActionPerformed

    private void S16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S16ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA24.getText());
        ++i;
        LA24.setText(String.valueOf(i));

        addtable(24,"Sponge cake",i,90.00);
        cal();
    }//GEN-LAST:event_S16ActionPerformed

    private void S15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S15ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA23.getText());
        ++i;
        LA23.setText(String.valueOf(i));

        addtable(23,"Sini Bun",i,90.00);
        cal();
    }//GEN-LAST:event_S15ActionPerformed

    private void S14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S14ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA22.getText());
        ++i;
        LA22.setText(String.valueOf(i));

        addtable(22,"Jam Bun",i,100.00);
        cal();
    }//GEN-LAST:event_S14ActionPerformed

    private void S13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S13ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA21.getText());
        ++i;
        LA21.setText(String.valueOf(i));

        addtable(21,"Eclairs",i,120.00);
        cal();
    }//GEN-LAST:event_S13ActionPerformed

    private void S12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S12ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA20.getText());
        ++i;
        LA20.setText(String.valueOf(i));

        addtable(20,"Croc Bun",i,90.00);
        cal();
    }//GEN-LAST:event_S12ActionPerformed

    private void S11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S11ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA19.getText());
        ++i;
        LA19.setText(String.valueOf(i));

        addtable(19,"Cream Bun",i,100.00);
        cal();
    }//GEN-LAST:event_S11ActionPerformed

    private void SE12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SE12ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA17.getText());
        ++i;
        LA17.setText(String.valueOf(i));

        addtable(17,"Drumstick bun",i,170.00);
        cal();
    }//GEN-LAST:event_SE12ActionPerformed

    private void SE11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SE11ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA16.getText());
        ++i;
        LA16.setText(String.valueOf(i));

        addtable(16,"Fish cake Bun",i,170.00);
        cal();
    }//GEN-LAST:event_SE11ActionPerformed

    private void SE10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SE10ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA15.getText());
        ++i;
        LA15.setText(String.valueOf(i));

        addtable(15,"Fish Bun",i,100.00);
        cal();
    }//GEN-LAST:event_SE10ActionPerformed

    private void SE9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SE9ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA14.getText());
        ++i;
        LA14.setText(String.valueOf(i));

        addtable(14,"Sinisambal Bun",i,100.00);
        cal();
    }//GEN-LAST:event_SE9ActionPerformed

    private void SE8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SE8ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA13.getText());
        ++i;
        LA13.setText(String.valueOf(i));

        addtable(13,"Sausage Jambo Bun",i,210.00);
        cal();
    }//GEN-LAST:event_SE8ActionPerformed

    private void SE7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SE7ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA12.getText());
        ++i;
        LA12.setText(String.valueOf(i));

        addtable(12,"Sausage Bun",i,110.00);
        cal();
    }//GEN-LAST:event_SE7ActionPerformed

    private void SE6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SE6ActionPerformed
        // TODO add your handling code here
        int i = Integer.valueOf(LA11.getText());
        ++i;
        LA11.setText(String.valueOf(i));

        addtable(11,"Omlet Bun",i,120.00);
        cal();
    }//GEN-LAST:event_SE6ActionPerformed

    private void SE5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SE5ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA10.getText());
        ++i;
        LA10.setText(String.valueOf(i));

        addtable(10,"Pizza",i,180.00);
        cal();
    }//GEN-LAST:event_SE5ActionPerformed

    private void SE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SE4ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA9.getText());
        ++i;
        LA9.setText(String.valueOf(i));

        addtable(9,"Egg Sinisambal Pastry",i,130.00);
        cal();
    }//GEN-LAST:event_SE4ActionPerformed

    private void SE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SE3ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA8.getText());
        ++i;
        LA8.setText(String.valueOf(i));

        addtable(8,"Chicken Pastry",i,140.00);
        cal();
    }//GEN-LAST:event_SE3ActionPerformed

    private void SE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SE2ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA7.getText());
        ++i;
        LA7.setText(String.valueOf(i));

        addtable(7,"Fish roll",i,110.00);
        cal();
    }//GEN-LAST:event_SE2ActionPerformed

    private void SE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SE1ActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(LA6.getText());
        ++i;
        LA6.setText(String.valueOf(i));

        addtable(6,"Egg roll",i,120.00);
        cal();
    }//GEN-LAST:event_SE1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton Back;
    private javax.swing.JLabel Bal;
    private javax.swing.JButton DI1;
    private javax.swing.JButton DI2;
    private javax.swing.JButton DR1;
    private javax.swing.JButton DR2;
    private javax.swing.JLabel LA1;
    private javax.swing.JLabel LA10;
    private javax.swing.JLabel LA11;
    private javax.swing.JLabel LA12;
    private javax.swing.JLabel LA13;
    private javax.swing.JLabel LA14;
    private javax.swing.JLabel LA15;
    private javax.swing.JLabel LA16;
    private javax.swing.JLabel LA17;
    private javax.swing.JLabel LA19;
    private javax.swing.JLabel LA2;
    private javax.swing.JLabel LA20;
    private javax.swing.JLabel LA21;
    private javax.swing.JLabel LA22;
    private javax.swing.JLabel LA23;
    private javax.swing.JLabel LA24;
    private javax.swing.JLabel LA29;
    private javax.swing.JLabel LA3;
    private javax.swing.JLabel LA30;
    private javax.swing.JLabel LA31;
    private javax.swing.JLabel LA32;
    private javax.swing.JLabel LA4;
    private javax.swing.JLabel LA5;
    private javax.swing.JLabel LA6;
    private javax.swing.JLabel LA7;
    private javax.swing.JLabel LA8;
    private javax.swing.JLabel LA9;
    private javax.swing.JButton S11;
    private javax.swing.JButton S12;
    private javax.swing.JButton S13;
    private javax.swing.JButton S14;
    private javax.swing.JButton S15;
    private javax.swing.JButton S16;
    private javax.swing.JButton SE1;
    private javax.swing.JButton SE10;
    private javax.swing.JButton SE11;
    private javax.swing.JButton SE12;
    private javax.swing.JButton SE2;
    private javax.swing.JButton SE3;
    private javax.swing.JButton SE4;
    private javax.swing.JButton SE5;
    private javax.swing.JButton SE6;
    private javax.swing.JButton SE7;
    private javax.swing.JButton SE8;
    private javax.swing.JButton SE9;
    private javax.swing.JLabel Tot;
    private javax.swing.JTextArea b;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pay;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
